### ISSUE TITLE
Add Model Performance Monitoring and Retraining Automation Features

### ISSUE THREAD

**Issue by PenHsuanWang** [PenHsuanWang/ml-system#16]
Two new features to the MLflow-based machine learning system: Model Performance Monitoring and Model Retraining Automation. These features will enhance the system's capability to monitor model performance continuously and trigger automated retraining based on predefined criteria.

**Features**:

1. **Model Performance Monitoring**:
    - **Design**:
        - Create a `ModelPerformanceMonitor` class that logs performance metrics at regular intervals.
    - **Implementation**:
    ```python
    # src/model_ops_manager/mlflow_agent/monitoring.py

    # Import necessary modules and classes

    class ModelPerformanceMonitor:
        def __init__(self, model_name, model_version, interval=60):
            # Initialize with model name, version, and monitoring interval
            pass

        def start_monitoring(self):
            # Start the monitoring thread
            pass

        def monitor_performance(self):
            # Continuously fetch and log metrics at defined intervals
            pass

        def fetch_metrics(self):
            # Implement logic to fetch performance metrics
            pass

        def log_metrics(self, metrics):
            # Log the fetched metrics
            pass
    ```

2. **Model Retraining Automation**:
    - **Design**:
        - Create a `ModelRetrainer` class that automates retraining based on predefined criteria.
    - **Implementation**:
    ```python
    # src/model_ops_manager/mlflow_agent/retrainer.py

    # Import necessary modules and classes

    class ModelRetrainer:
        def __init__(self, retraining_script, criteria):
            # Initialize with retraining script and criteria
            pass

        def check_and_retrain(self, model_name, model_version):
            # Check if retraining criteria are met and retrain model if necessary
            pass

        def get_run_id(self, model_name, model_version):
            # Get the run ID for a specific model version
            pass

        def should_retrain(self, metrics):
            # Determine if retraining is needed based on metrics
            pass

        def retrain_model(self):
            # Execute the retraining script
            pass
    ```

**Tasks**:
- [ ] Implement `ModelPerformanceMonitor` class in `monitoring.py`.
- [ ] Implement `ModelRetrainer` class in `retrainer.py`.
- [ ] Test the performance monitoring functionality.
- [ ] Test the retraining automation functionality.
- [ ] Update documentation to reflect new features.
- [ ] Review and merge the changes.
